# Generated by Django 6.0.6 on 2026-07-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "verbose_name": "Book (စာအုပ်)",
                "verbose_name_plural": "Books (စာအုပ်များ)",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Category (အမျိုးအစား)",
                "verbose_name_plural": "Categories (အမျိုးအစားများ)",
            },
        ),
    ]
