# Generated by Django 6.0.6 on 2026-07-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_options_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="code_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="University Code Number",
            ),
        ),
    ]
