# Generated by Django 6.0.6 on 2026-06-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="is_librarian",),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Super Admin"),
                    ("librarian", "Librarian/Staff"),
                    ("student", "Student Member"),
                ],
                default="student",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="student_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
