# Generated by Django 6.0.6 on 2026-06-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_customuser_is_librarian_customuser_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
